[package]
name = "aoc2025-dwarf"
version = "0.1.0"
edition = "2024"

[dependencies]
gimli = "0.32.3"
object = { version = "0.37.3", features = ["write_core"] }
chumsky = "0.11.2"
ariadne = "0.6.0"
itertools = "0.14.0"
indent_write = "2.2.0"
